# Generated by Django 4.2.1 on 2023-05-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='units_currency',
            field=models.CharField(default='USD', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='units_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
