# Generated by Django 4.2.1 on 2023-05-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_posting_units_currency_posting_units_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='units_number',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
